name: DemoCICD

run-name: Running ${{ github.workflow }} on ${{ github.event_name }} by @${{ github.actor }} - ${{ github.event.merge_group.head_commit.message }}

on:
  merge_group:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        API_KEY: ${{ secrets.TEST_APIKEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world! test job 1! APIKEY = '${{ env.API_KEY }}'
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: build

    steps:
      - name: Run a multi-line script
        run: |
          echo test job 2
          echo primeiro
          echo '${{ github.head_ref }}'
          echo segundo
          echo '${{ github.ref }}'
