---
name: Merge Gatekeeper

on:
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  merge-gatekeeper:
    name: merge-gatekeeper
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Merge Gatekeeper in Merge Queue
        if: github.event_name == 'merge_group'
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.CICD_TOKEN }}
          ref: ${{github.ref}}
          timeout: 2400
